name: flutter_snackbar_plus
description: A minimal library to handle SnackBars with elaborate list of configuration & style options.
version: 1.0.0
homepage: https://github.com/micazi/flutter_snackbar_plus

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
